artifact_location: file:///C:/Users/Magnus/PycharmProjects/LSDA_assignment2/--default-artifact-root/0
creation_time: 1678457331839
experiment_id: '0'
last_update_time: 1678457331839
lifecycle_stage: active
name: Default
